name: Codestyle checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  codestyle:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setting up Python dependencies
        if: ${{ always() }}
        run: python -m pip install -r requirements.txt
      - name: Setting up Python codestyle checks/test dependencies
        if: ${{ always() }}
        run: python -m pip install -r requirements_dev.txt

      - name: Running Bandit
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: python -m bandit -r ./ -f screen
          
      - name: Running PEP checks
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: python -m flake8 ./ --config=setup.cfg --show-source

      - name: Running MyPy checks
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: python -m mypy ./ --config-file ./setup.cfg --show-error-context --show-column-numbers --pretty

      - name: Running pytest (not Docker image tests)
        if: ${{ always() }}
        run: python -m pytest ./utils/tests --self-contained-html --html=utils_unittests.html

      - name: Collecting codestyle artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: codestyle_checks
          path: |
            ./utils_unittests.html